package gdn.hypercube.appetizers.init;

import gdn.hypercube.appetizers.item.AppetizingFoodItem;
import gdn.hypercube.appetizers.util.effect.AntifreezeConsumeEffect;
import gdn.hypercube.appetizers.util.effect.DrGibbConsumeEffect;
import gdn.hypercube.appetizers.util.effect.MREConsumeEffect;
import java.util.ArrayList;
import java.util.List;
import net.minecraft.entity.effect.StatusEffectInstance;
import net.minecraft.entity.effect.StatusEffects;
import net.minecraft.item.consume.ApplyEffectsConsumeEffect;
import net.minecraft.item.consume.ClearAllEffectsConsumeEffect;
import net.minecraft.sound.SoundEvents;

public class AppetizersDrinks {
    private static final List<StatusEffectInstance> atpunch = new ArrayList<>();
    private static final List<StatusEffectInstance> ddelight = new ArrayList<>();
    private static final List<StatusEffectInstance> drblood = new ArrayList<>();
    private static final List<StatusEffectInstance> drbreath = new ArrayList<>();
    private static final List<StatusEffectInstance> floko = new ArrayList<>();
    private static final List<StatusEffectInstance> toxins = new ArrayList<>();
    private static final StatusEffectInstance glowing = new StatusEffectInstance(StatusEffects.GLOWING, 1200);

    public static void init() {
        AppetizersInit.register(new AppetizingFoodItem("7deadlysins", "", true, 4, 4, SoundEvents.ENTITY_GENERIC_DRINK, 2.25F), "7deadlysins");
        AppetizersInit.register(new AppetizingFoodItem("absintheglass", "", true, 4, 4, SoundEvents.ENTITY_GENERIC_DRINK, 2.25F), "absintheglass");
        AppetizersInit.register(new AppetizingFoodItem("acidspitglass", "", true, 4, 4, SoundEvents.ENTITY_GENERIC_DRINK, 2.25F), "acidspitglass");
        AppetizersInit.register(new AppetizingFoodItem("aleglass", "", true, 4, 4, SoundEvents.ENTITY_GENERIC_DRINK, 2.25F), "aleglass");
        AppetizersInit.register(new AppetizingFoodItem("alienbrainhemorrhage", "", true, 4, 4, SoundEvents.ENTITY_GENERIC_DRINK, 2.25F), "alienbrainhemorrhage");
        AppetizersInit.register(new AppetizingFoodItem("alliescocktail", "", true, 4, 4, SoundEvents.ENTITY_GENERIC_DRINK, 2.25F), "alliescocktail");
        AppetizersInit.register(new AppetizingFoodItem("aloe", "", true, 4, 4, SoundEvents.ENTITY_GENERIC_DRINK, 2.25F), "aloe");
        AppetizersInit.register(new AppetizingFoodItem("amasecglass", "", true, 4, 4, SoundEvents.ENTITY_GENERIC_DRINK, 2.25F), "amasecglass");
        AppetizersInit.register(new AppetizingFoodItem("andalusia", "", true, 4, 4, SoundEvents.ENTITY_GENERIC_DRINK, 2.25F), "andalusia");
        AppetizersInit.register(new AppetizingFoodItem("antifreeze", "The forbidden juice.", true, 4, 4, SoundEvents.ENTITY_GENERIC_DRINK, 2.25F, AntifreezeConsumeEffect.INSTANCE), "antifreeze");
        AppetizersInit.register(new AppetizingFoodItem("appleberryfizz", "", true, 4, 4, SoundEvents.ENTITY_GENERIC_DRINK, 2.25F), "appleberryfizz");
        AppetizersInit.register(new AppetizingFoodItem("arnoldpalmer", "", true, 4, 4, SoundEvents.ENTITY_GENERIC_DRINK, 2.25F), "arnoldpalmer");
        AppetizersInit.register(new AppetizingFoodItem("atomicbombglass", "", true, 4, 4, SoundEvents.ENTITY_GENERIC_DRINK, 2.25F), "atomicbombglass");
        AppetizersInit.register(new AppetizingFoodItem("atomicpunch", "Birds fly, grass grows, sun shines...", true, 4, 4, SoundEvents.ENTITY_GENERIC_DRINK, 2.25F, new ApplyEffectsConsumeEffect(atpunch)), "atomicpunch");
        AppetizersInit.register(new AppetizingFoodItem("bnp", "", true, 4, 4, SoundEvents.ENTITY_GENERIC_DRINK, 2.25F), "bnp");
        AppetizersInit.register(new AppetizingFoodItem("b52glass", "", true, 4, 4, SoundEvents.ENTITY_GENERIC_DRINK, 2.25F), "b52glass");
        AppetizersInit.register(new AppetizingFoodItem("bacchusblessing", "", true, 4, 4, SoundEvents.ENTITY_GENERIC_DRINK, 2.25F), "bacchusblessing");
        AppetizersInit.register(new AppetizingFoodItem("bahama_mama", "", true, 4, 4, SoundEvents.ENTITY_GENERIC_DRINK, 2.25F), "bahama_mama");
        AppetizersInit.register(new AppetizingFoodItem("banana", "", true, 4, 4, SoundEvents.ENTITY_GENERIC_DRINK, 2.25F), "banana");
        AppetizersInit.register(new AppetizingFoodItem("bananahonkglass", "", true, 4, 4, SoundEvents.ENTITY_GENERIC_DRINK, 2.25F), "bananahonkglass");
        AppetizersInit.register(new AppetizingFoodItem("bande", "", true, 4, 4, SoundEvents.ENTITY_GENERIC_DRINK, 2.25F), "bande");
        AppetizersInit.register(new AppetizingFoodItem("beepskysmashglass", "Stop! You violated the law.", true, 4, 4, SoundEvents.ENTITY_GENERIC_DRINK, 2.25F), "beepskysmashglass");
        AppetizersInit.register(new AppetizingFoodItem("beerglass", "", true, 4, 4, SoundEvents.ENTITY_GENERIC_DRINK, 2.25F), "beerglass");
        AppetizersInit.register(new AppetizingFoodItem("beesknees", "", true, 4, 4, SoundEvents.ENTITY_GENERIC_DRINK, 2.25F), "beesknees");
        AppetizersInit.register(new AppetizingFoodItem("berryjuice", "", true, 4, 4, SoundEvents.ENTITY_GENERIC_DRINK, 2.25F), "berryjuice");
        AppetizersInit.register(new AppetizingFoodItem("blackrussianglass", "", true, 4, 4, SoundEvents.ENTITY_GENERIC_DRINK, 2.25F), "blackrussianglass");
        AppetizersInit.register(new AppetizingFoodItem("bloodglass", "", true, 4, 4, SoundEvents.ENTITY_GENERIC_DRINK, 2.25F, new ApplyEffectsConsumeEffect(new StatusEffectInstance(StatusEffects.REGENERATION, 300))), "bloodglass");
        AppetizersInit.register(new AppetizingFoodItem("bloodymaryglass", "", true, 4, 4, SoundEvents.ENTITY_GENERIC_DRINK, 2.25F), "bloodymaryglass");
        AppetizersInit.register(new AppetizingFoodItem("bluehawaiian", "", true, 4, 4, SoundEvents.ENTITY_GENERIC_DRINK, 2.25F), "bluehawaiian");
        AppetizersInit.register(new AppetizingFoodItem("brainbomb", "", true, 4, 4, SoundEvents.ENTITY_GENERIC_DRINK, 2.25F), "brainbomb");
        AppetizersInit.register(new AppetizingFoodItem("bravebullglass", "", true, 4, 4, SoundEvents.ENTITY_GENERIC_DRINK, 2.25F), "bravebullglass");
        AppetizersInit.register(new AppetizingFoodItem("bronx", "", true, 4, 4, SoundEvents.ENTITY_GENERIC_DRINK, 2.25F), "bronx");
        AppetizersInit.register(new AppetizingFoodItem("brownstar", "", true, 4, 4, SoundEvents.ENTITY_GENERIC_DRINK, 2.25F), "brownstar");
        AppetizersInit.register(new AppetizingFoodItem("bubbletea", "", true, 4, 4, SoundEvents.ENTITY_GENERIC_DRINK, 2.25F), "bubbletea");
        AppetizersInit.register(new AppetizingFoodItem("budgetinsulsdrink", "Tider's favourite.", true, 4, 4, SoundEvents.ENTITY_GENERIC_DRINK, 2.25F), "budgetinsulsdrink");
        AppetizersInit.register(new AppetizingFoodItem("cafedecacao", "", true, 4, 4, SoundEvents.ENTITY_GENERIC_DRINK, 2.25F), "cafedecacao");
        AppetizersInit.register(new AppetizingFoodItem("caipirinha", "", true, 4, 4, SoundEvents.ENTITY_GENERIC_DRINK, 2.25F), "caipirinha");
        AppetizersInit.register(new AppetizingFoodItem("calicosunrise", "", true, 4, 4, SoundEvents.ENTITY_GENERIC_DRINK, 2.25F), "calicosunrise");
        AppetizersInit.register(new AppetizingFoodItem("carrotjuice", "", true, 4, 4, SoundEvents.ENTITY_GENERIC_DRINK, 2.25F), "carrotjuice");
        AppetizersInit.register(new AppetizingFoodItem("champagneglass", "", true, 4, 4, SoundEvents.ENTITY_GENERIC_DRINK, 2.25F), "champagneglass");
        AppetizersInit.register(new AppetizingFoodItem("chocolateglass", "", true, 4, 4, SoundEvents.ENTITY_GENERIC_DRINK, 2.25F), "chocolateglass");
        AppetizersInit.register(new AppetizingFoodItem("circusjuice", "", true, 4, 4, SoundEvents.ENTITY_GENERIC_DRINK, 2.25F), "circusjuice");
        AppetizersInit.register(new AppetizingFoodItem("clownblood", "", true, 4, 4, SoundEvents.ENTITY_GENERIC_DRINK, 2.25F, new ApplyEffectsConsumeEffect(new StatusEffectInstance(StatusEffects.REGENERATION, 300, 1))), "clownblood");
        AppetizersInit.register(new AppetizingFoodItem("coconutrum", "", true, 4, 4, SoundEvents.ENTITY_GENERIC_DRINK, 2.25F), "coconutrum");
        AppetizersInit.register(new AppetizingFoodItem("coffeeglass", "", true, 4, 4, SoundEvents.ENTITY_GENERIC_DRINK, 2.25F, new ApplyEffectsConsumeEffect(new StatusEffectInstance(StatusEffects.SPEED, 600, 1))), "coffeeglass");
        AppetizersInit.register(new AppetizingFoodItem("coffeeliqueurglass", "", true, 4, 4, SoundEvents.ENTITY_GENERIC_DRINK, 2.25F), "coffeeliqueurglass");
        AppetizersInit.register(new AppetizingFoodItem("cogchamp", "Qevax Jryy!", true, 4, 4, SoundEvents.ENTITY_GENERIC_DRINK, 2.25F, new ApplyEffectsConsumeEffect(new StatusEffectInstance(AppetizersInit.COGCHAMP, 1200))), "cogchamp");
        AppetizersInit.register(new AppetizingFoodItem("cognacglass", "", true, 4, 4, SoundEvents.ENTITY_GENERIC_DRINK, 2.25F), "cognacglass");
        AppetizersInit.register(new AppetizingFoodItem("colaglass", "", true, 4, 4, SoundEvents.ENTITY_GENERIC_DRINK, 2.25F), "colaglass");
        AppetizersInit.register(new AppetizingFoodItem("cosmopolitan", "", true, 4, 4, SoundEvents.ENTITY_GENERIC_DRINK, 2.25F), "cosmopolitan");
        AppetizersInit.register(new AppetizingFoodItem("creambar", "", true, 4, 4, SoundEvents.ENTITY_GENERIC_DRINK, 2.25F), "creambar");
        AppetizersInit.register(new AppetizingFoodItem("cremedecacao", "", true, 4, 4, SoundEvents.ENTITY_GENERIC_DRINK, 2.25F), "cremedecacao");
        AppetizersInit.register(new AppetizingFoodItem("crushdepth", "", true, 4, 4, SoundEvents.ENTITY_GENERIC_DRINK, 2.25F), "crushdepth");
        AppetizersInit.register(new AppetizingFoodItem("cubalibreglass", "", true, 4, 4, SoundEvents.ENTITY_GENERIC_DRINK, 2.25F), "cubalibreglass");
        AppetizersInit.register(new AppetizingFoodItem("cucumberwater", "", true, 4, 4, SoundEvents.ENTITY_GENERIC_DRINK, 2.25F), "cucumberwater");
        AppetizersInit.register(new AppetizingFoodItem("curacaoglass", "", true, 4, 4, SoundEvents.ENTITY_GENERIC_DRINK, 2.25F), "curacaoglass");
        AppetizersInit.register(new AppetizingFoodItem("daiquiri", "", true, 4, 4, SoundEvents.ENTITY_GENERIC_DRINK, 2.25F), "daiquiri");
        AppetizersInit.register(new AppetizingFoodItem("darknstormy", "", true, 4, 4, SoundEvents.ENTITY_GENERIC_DRINK, 2.25F), "darknstormy");
        AppetizersInit.register(new AppetizingFoodItem("darkoasis", "", true, 4, 4, SoundEvents.ENTITY_GENERIC_DRINK, 2.25F), "darkoasis");
        AppetizersInit.register(new AppetizingFoodItem("davenport", "Does not contain pufferfish.", true, 4, 4, SoundEvents.ENTITY_GENERIC_DRINK, 2.25F), "davenport");
        AppetizersInit.register(new AppetizingFoodItem("deadmansdraught", "", true, 4, 4, SoundEvents.ENTITY_GENERIC_DRINK, 2.25F), "deadmansdraught");
        AppetizersInit.register(new AppetizingFoodItem("deathintheafternoon", "", true, 4, 4, SoundEvents.ENTITY_GENERIC_DRINK, 2.25F), "deathintheafternoon");
        AppetizersInit.register(new AppetizingFoodItem("demonsblood", "", true, 4, 4, SoundEvents.ENTITY_GENERIC_DRINK, 2.25F, new ApplyEffectsConsumeEffect(new StatusEffectInstance(StatusEffects.REGENERATION, 600, 2))), "demonsblood");
        AppetizersInit.register(new AppetizingFoodItem("devilskiss", "", true, 4, 4, SoundEvents.ENTITY_GENERIC_DRINK, 2.25F), "devilskiss");
        AppetizersInit.register(new AppetizingFoodItem("dirtywastelander", "", true, 4, 4, SoundEvents.ENTITY_GENERIC_DRINK, 2.25F), "dirtywastelander");
        AppetizersInit.register(new AppetizingFoodItem("doctorsdelightglass", "", true, 4, 4, SoundEvents.ENTITY_GENERIC_DRINK, 2.25F, new ApplyEffectsConsumeEffect(ddelight)), "doctorsdelightglass");
        AppetizersInit.register(new AppetizingFoodItem("doublecreamblaster", "", true, 4, 4, SoundEvents.ENTITY_GENERIC_DRINK, 2.25F), "doublecreamblaster");
        AppetizersInit.register(new AppetizingFoodItem("dr_gibb_glass", "May contain malpractice.", true, 4, 4, SoundEvents.ENTITY_GENERIC_DRINK, 2.25F, DrGibbConsumeEffect.INSTANCE), "dr_gibb_glass");
        AppetizersInit.register(new AppetizingFoodItem("dragonsblood", "", true, 4, 4, SoundEvents.ENTITY_GENERIC_DRINK, 2.25F, new ApplyEffectsConsumeEffect(drblood)), "dragonsblood");
        AppetizersInit.register(new AppetizingFoodItem("dragonsbreath", "", true, 4, 4, SoundEvents.ENTITY_GENERIC_DRINK, 2.25F, new ApplyEffectsConsumeEffect(drbreath)), "dragonsbreath");
        AppetizersInit.register(new AppetizingFoodItem("driestmartiniglass", "", true, 4, 4, SoundEvents.ENTITY_GENERIC_DRINK, 2.25F), "driestmartiniglass");
        AppetizersInit.register(new AppetizingFoodItem("eggnogglass", "", true, 4, 4, SoundEvents.ENTITY_GENERIC_DRINK, 2.25F), "eggnogglass");
        AppetizersInit.register(new AppetizingFoodItem("electricshark", "", true, 4, 4, SoundEvents.ENTITY_GENERIC_DRINK, 2.25F), "electricshark");
        AppetizersInit.register(new AppetizingFoodItem("emeraldglass", "", true, 4, 4, SoundEvents.ENTITY_GENERIC_DRINK, 2.25F, new ApplyEffectsConsumeEffect(new StatusEffectInstance(StatusEffects.HERO_OF_THE_VILLAGE, 6000, 4))), "emeraldglass");
        AppetizersInit.register(new AppetizingFoodItem("eminence", "Often called the \"nectar of the gods\".\nThe label doesn't say which ones, though.", true, 4, 4, SoundEvents.ENTITY_GENERIC_DRINK, 2.25F, MREConsumeEffect.INSTANCE), "eminence");
        AppetizersInit.register(new AppetizingFoodItem("empress75", "", true, 4, 4, SoundEvents.ENTITY_GENERIC_DRINK, 2.25F), "empress75");
        AppetizersInit.register(new AppetizingFoodItem("erikasurprise", "", true, 4, 4, SoundEvents.ENTITY_GENERIC_DRINK, 2.25F), "erikasurprise");
        AppetizersInit.register(new AppetizingFoodItem("espressomartini", "", true, 4, 4, SoundEvents.ENTITY_GENERIC_DRINK, 2.25F), "espressomartini");
        AppetizersInit.register(new AppetizingFoodItem("feverdream", "", true, 4, 4, SoundEvents.ENTITY_GENERIC_DRINK, 2.25F), "feverdream");
        AppetizersInit.register(new AppetizingFoodItem("fourteen_loko_glass", "Your heart will hate you.", true, 4, 4, SoundEvents.ENTITY_GENERIC_DRINK, 2.25F, new ApplyEffectsConsumeEffect(floko)), "fourteen_loko_glass");
        AppetizersInit.register(new AppetizingFoodItem("gargleblasterglass", "Do you know where your towel is?", true, 4, 4, SoundEvents.ENTITY_GENERIC_DRINK, 2.25F), "gargleblasterglass");
        AppetizersInit.register(new AppetizingFoodItem("gildlagerglass", "", true, 4, 4, SoundEvents.ENTITY_GENERIC_DRINK, 2.25F), "gildlagerglass");
        AppetizersInit.register(new AppetizingFoodItem("ginfizzglass", "", true, 4, 4, SoundEvents.ENTITY_GENERIC_DRINK, 2.25F), "ginfizzglass");
        AppetizersInit.register(new AppetizingFoodItem("gintonicglass", "", true, 4, 4, SoundEvents.ENTITY_GENERIC_DRINK, 2.25F), "gintonicglass");
        AppetizersInit.register(new AppetizingFoodItem("ginvodkaglass", "", true, 4, 4, SoundEvents.ENTITY_GENERIC_DRINK, 2.25F), "ginvodkaglass");
        AppetizersInit.register(new AppetizingFoodItem("goldbloomspecial", "", true, 4, 4, SoundEvents.ENTITY_GENERIC_DRINK, 2.25F), "goldbloomspecial");
        AppetizersInit.register(new AppetizingFoodItem("grandnavy", "", true, 4, 4, SoundEvents.ENTITY_GENERIC_DRINK, 2.25F), "grandnavy");
        AppetizersInit.register(new AppetizingFoodItem("grapejuice", "", true, 4, 4, SoundEvents.ENTITY_GENERIC_DRINK, 2.25F), "grapejuice");
        AppetizersInit.register(new AppetizingFoodItem("graveyard", "WARNING: May cause existential dread.", true, 4, 4, SoundEvents.ENTITY_GENERIC_DRINK, 2.25F, new ApplyEffectsConsumeEffect(new StatusEffectInstance(AppetizersInit.DREAD, 12000))), "graveyard");
        AppetizersInit.register(new AppetizingFoodItem("greenteaglass", "", true, 4, 4, SoundEvents.ENTITY_GENERIC_DRINK, 2.25F), "greenteaglass");
        AppetizersInit.register(new AppetizingFoodItem("grenadineglass", "", true, 4, 4, SoundEvents.ENTITY_GENERIC_DRINK, 2.25F), "grenadineglass");
        AppetizersInit.register(new AppetizingFoodItem("grogglass", "Won't remove nanomachines.", true, 4, 4, SoundEvents.ENTITY_GENERIC_DRINK, 2.25F, new ClearAllEffectsConsumeEffect()), "grogglass");
        AppetizersInit.register(new AppetizingFoodItem("gsodaglass", "", true, 4, 4, SoundEvents.ENTITY_GENERIC_DRINK, 2.25F), "gsodaglass");
        AppetizersInit.register(new AppetizingFoodItem("heartbreakmountain", "", true, 4, 4, SoundEvents.ENTITY_GENERIC_DRINK, 2.25F), "heartbreakmountain");
        AppetizersInit.register(new AppetizingFoodItem("hippiesdelightglass", "", true, 4, 4, SoundEvents.ENTITY_GENERIC_DRINK, 2.25F), "hippiesdelightglass");
        AppetizersInit.register(new AppetizingFoodItem("holyvice", "", true, 4, 4, SoundEvents.ENTITY_GENERIC_DRINK, 2.25F), "holyvice");
        AppetizersInit.register(new AppetizingFoodItem("icecreamglass", "", true, 4, 4, SoundEvents.ENTITY_GENERIC_DRINK, 2.25F), "icecreamglass");
        AppetizersInit.register(new AppetizingFoodItem("iced_beerglass", "", true, 4, 4, SoundEvents.ENTITY_GENERIC_DRINK, 2.25F), "iced_beerglass");
        AppetizersInit.register(new AppetizingFoodItem("icedcoffeeglass", "", true, 4, 4, SoundEvents.ENTITY_GENERIC_DRINK, 2.25F), "icedcoffeeglass");
        AppetizersInit.register(new AppetizingFoodItem("icedgreenteaglass", "", true, 4, 4, SoundEvents.ENTITY_GENERIC_DRINK, 2.25F), "icedgreenteaglass");
        AppetizersInit.register(new AppetizingFoodItem("icedteaglass", "", true, 4, 4, SoundEvents.ENTITY_GENERIC_DRINK, 2.25F), "icedteaglass");
        AppetizersInit.register(new AppetizingFoodItem("iceglass", "", true, 4, 4, SoundEvents.ENTITY_GENERIC_DRINK, 2.25F, new ApplyEffectsConsumeEffect(new StatusEffectInstance(StatusEffects.SLOWNESS, 600, 1))), "iceglass");
        AppetizersInit.register(new AppetizingFoodItem("irishcoffeeglass", "", true, 4, 4, SoundEvents.ENTITY_GENERIC_DRINK, 2.25F), "irishcoffeeglass");
        AppetizersInit.register(new AppetizingFoodItem("irishcreamglass", "", true, 4, 4, SoundEvents.ENTITY_GENERIC_DRINK, 2.25F), "irishcreamglass");
        AppetizersInit.register(new AppetizingFoodItem("irishslammer", "", true, 4, 4, SoundEvents.ENTITY_GENERIC_DRINK, 2.25F), "irishslammer");
        AppetizersInit.register(new AppetizingFoodItem("jackrose", "", true, 4, 4, SoundEvents.ENTITY_GENERIC_DRINK, 2.25F), "jackrose");
        AppetizersInit.register(new AppetizingFoodItem("junglebird", "", true, 4, 4, SoundEvents.ENTITY_GENERIC_DRINK, 2.25F), "junglebird");
        AppetizersInit.register(new AppetizingFoodItem("kalimotxo", "", true, 4, 4, SoundEvents.ENTITY_GENERIC_DRINK, 2.25F), "kalimotxo");
        AppetizersInit.register(new AppetizingFoodItem("kiraspecial", "", true, 4, 4, SoundEvents.ENTITY_GENERIC_DRINK, 2.25F), "kiraspecial");
        AppetizersInit.register(new AppetizingFoodItem("kvass", "", true, 4, 4, SoundEvents.ENTITY_GENERIC_DRINK, 2.25F), "kvass");
        AppetizersInit.register(new AppetizingFoodItem("lamplight", "oh goodness gracious I'm stuck in an elevator with the messiah and also literally god themself", true, 4, 4, SoundEvents.ENTITY_GENERIC_DRINK, 2.25F, new ApplyEffectsConsumeEffect(glowing)), "lamplight");
        AppetizersInit.register(new AppetizingFoodItem("lean", "", true, 4, 4, SoundEvents.ENTITY_GENERIC_DRINK, 2.25F), "lean");
        AppetizersInit.register(new AppetizingFoodItem("lemonade", "", true, 4, 4, SoundEvents.ENTITY_GENERIC_DRINK, 2.25F), "lemonade");
        AppetizersInit.register(new AppetizingFoodItem("lemonadeglass", "", true, 4, 4, SoundEvents.ENTITY_GENERIC_DRINK, 2.25F), "lemonadeglass");
        AppetizersInit.register(new AppetizingFoodItem("lemonglass", "", true, 4, 4, SoundEvents.ENTITY_GENERIC_DRINK, 2.25F), "lemonglass");
        AppetizersInit.register(new AppetizingFoodItem("lemonjuiceglass", "", true, 4, 4, SoundEvents.ENTITY_GENERIC_DRINK, 2.25F), "lemonjuiceglass");
        AppetizersInit.register(new AppetizingFoodItem("lemonlime", "", true, 4, 4, SoundEvents.ENTITY_GENERIC_DRINK, 2.25F), "lemonlime");
        AppetizersInit.register(new AppetizingFoodItem("lemonpopsicle", "", true, 4, 4, SoundEvents.ENTITY_GENERIC_DRINK, 2.25F), "lemonpopsicle");
        AppetizersInit.register(new AppetizingFoodItem("longislandicedteaglass", "", true, 4, 4, SoundEvents.ENTITY_GENERIC_DRINK, 2.25F), "longislandicedteaglass");
        AppetizersInit.register(new AppetizingFoodItem("loverskiss", "", true, 4, 4, SoundEvents.ENTITY_GENERIC_DRINK, 2.25F), "loverskiss");
        AppetizersInit.register(new AppetizingFoodItem("manhattanglass", "", true, 4, 4, SoundEvents.ENTITY_GENERIC_DRINK, 2.25F), "manhattanglass");
        AppetizersInit.register(new AppetizingFoodItem("manlydorfglass", "", true, 4, 4, SoundEvents.ENTITY_GENERIC_DRINK, 2.25F, new ApplyEffectsConsumeEffect(new StatusEffectInstance(StatusEffects.HASTE, 1200, 1))), "manlydorfglass");
        AppetizersInit.register(new AppetizingFoodItem("margaritaglass", "", true, 4, 4, SoundEvents.ENTITY_GENERIC_DRINK, 2.25F), "margaritaglass");
        AppetizersInit.register(new AppetizingFoodItem("mariejulep", "", true, 4, 4, SoundEvents.ENTITY_GENERIC_DRINK, 2.25F), "mariejulep");
        AppetizersInit.register(new AppetizingFoodItem("martiniglass", "", true, 4, 4, SoundEvents.ENTITY_GENERIC_DRINK, 2.25F), "martiniglass");
        AppetizersInit.register(new AppetizingFoodItem("mayojito", "Revolting.", true, 4, 4, SoundEvents.ENTITY_GENERIC_DRINK, 2.25F, new ApplyEffectsConsumeEffect(new StatusEffectInstance(StatusEffects.POISON, 600))), "mayojito");
        AppetizersInit.register(new AppetizingFoodItem("meadglass", "", true, 4, 4, SoundEvents.ENTITY_GENERIC_DRINK, 2.25F), "meadglass");
        AppetizersInit.register(new AppetizingFoodItem("milkshake", "", true, 4, 4, SoundEvents.ENTITY_GENERIC_DRINK, 2.25F), "milkshake");
        AppetizersInit.register(new AppetizingFoodItem("mimeosa", "...", true, 4, 4, SoundEvents.ENTITY_GENERIC_DRINK, 2.25F, new ApplyEffectsConsumeEffect(new StatusEffectInstance(AppetizersInit.SILENCED, 1200))), "mimeosa");
        AppetizersInit.register(new AppetizingFoodItem("mimosa", "", true, 4, 4, SoundEvents.ENTITY_GENERIC_DRINK, 2.25F), "mimosa");
        AppetizersInit.register(new AppetizingFoodItem("mojito", "", true, 4, 4, SoundEvents.ENTITY_GENERIC_DRINK, 2.25F), "mojito");
        AppetizersInit.register(new AppetizingFoodItem("monkeybusiness", "", true, 4, 4, SoundEvents.ENTITY_GENERIC_DRINK, 2.25F), "monkeybusiness");
        AppetizersInit.register(new AppetizingFoodItem("moonshineglass", "", true, 4, 4, SoundEvents.ENTITY_GENERIC_DRINK, 2.25F), "moonshineglass");
        AppetizersInit.register(new AppetizingFoodItem("moscowmule", "", true, 4, 4, SoundEvents.ENTITY_GENERIC_DRINK, 2.25F), "moscowmule");
        AppetizersInit.register(new AppetizingFoodItem("neurotoxinglass", "Why would you drink this?", true, 4, 4, SoundEvents.ENTITY_GENERIC_DRINK, 2.25F, new ApplyEffectsConsumeEffect(new StatusEffectInstance(StatusEffects.WITHER, 1200, 9))), "neurotoxinglass");
        AppetizersInit.register(new AppetizingFoodItem("nuclear_colaglass", "", true, 4, 4, SoundEvents.ENTITY_GENERIC_DRINK, 2.25F), "nuclear_colaglass");
        AppetizersInit.register(new AppetizingFoodItem("numberone", "", true, 4, 4, SoundEvents.ENTITY_GENERIC_DRINK, 2.25F), "numberone");
        AppetizersInit.register(new AppetizingFoodItem("orangecreamcicle", "", true, 4, 4, SoundEvents.ENTITY_GENERIC_DRINK, 2.25F), "orangecreamcicle");
        AppetizersInit.register(new AppetizingFoodItem("orangejuiceglass", "", true, 4, 4, SoundEvents.ENTITY_GENERIC_DRINK, 2.25F), "orangejuiceglass");
        AppetizersInit.register(new AppetizingFoodItem("painkiller", "", true, 4, 4, SoundEvents.ENTITY_GENERIC_DRINK, 2.25F), "painkiller");
        AppetizersInit.register(new AppetizingFoodItem("patronglass", "", true, 4, 4, SoundEvents.ENTITY_GENERIC_DRINK, 2.25F), "patronglass");
        AppetizersInit.register(new AppetizingFoodItem("pinacolada", "No, it won't open a portal.", true, 4, 4, SoundEvents.ENTITY_GENERIC_DRINK, 2.25F), "pinacolada");
        AppetizersInit.register(new AppetizingFoodItem("pineappleblast", "Special edition!", true, 4, 4, SoundEvents.ENTITY_GENERIC_DRINK, 2.25F), "pineappleblast");
        AppetizersInit.register(new AppetizingFoodItem("pinkdrink", "", true, 4, 4, SoundEvents.ENTITY_GENERIC_DRINK, 2.25F), "pinkdrink");
        AppetizersInit.register(new AppetizingFoodItem("poisonberryjuice", "", true, 4, 4, SoundEvents.ENTITY_GENERIC_DRINK, 2.25F, new ApplyEffectsConsumeEffect(new StatusEffectInstance(StatusEffects.POISON, 600, 3))), "poisonberryjuice");
        AppetizersInit.register(new AppetizingFoodItem("pomonade", "", true, 4, 4, SoundEvents.ENTITY_GENERIC_DRINK, 2.25F), "pomonade");
        AppetizersInit.register(new AppetizingFoodItem("pompassion", "", true, 4, 4, SoundEvents.ENTITY_GENERIC_DRINK, 2.25F), "pompassion");
        AppetizersInit.register(new AppetizingFoodItem("pomtwist", "", true, 4, 4, SoundEvents.ENTITY_GENERIC_DRINK, 2.25F), "pomtwist");
        AppetizersInit.register(new AppetizingFoodItem("prairieoyster", "", true, 4, 4, SoundEvents.ENTITY_GENERIC_DRINK, 2.25F), "prairieoyster");
        AppetizersInit.register(new AppetizingFoodItem("prisonwine", "", true, 4, 4, SoundEvents.ENTITY_GENERIC_DRINK, 2.25F), "prisonwine");
        AppetizersInit.register(new AppetizingFoodItem("proj_manhattanglass", "", true, 4, 4, SoundEvents.ENTITY_GENERIC_DRINK, 2.25F), "proj_manhattanglass");
        AppetizersInit.register(new AppetizingFoodItem("pumpkinspicelatte", "", true, 4, 4, SoundEvents.ENTITY_GENERIC_DRINK, 2.25F), "pumpkinspicelatte");
        AppetizersInit.register(new AppetizingFoodItem("pwineglass", "", true, 4, 4, SoundEvents.ENTITY_GENERIC_DRINK, 2.25F, new ApplyEffectsConsumeEffect(new StatusEffectInstance(StatusEffects.POISON, 600, 3))), "pwineglass");
        AppetizersInit.register(new AppetizingFoodItem("quadruplecreamchalice", "", true, 4, 4, SoundEvents.ENTITY_GENERIC_DRINK, 2.25F), "quadruplecreamchalice");
        AppetizersInit.register(new AppetizingFoodItem("radler", "", true, 4, 4, SoundEvents.ENTITY_GENERIC_DRINK, 2.25F), "radler");
        AppetizersInit.register(new AppetizingFoodItem("red_meadglass", "", true, 4, 4, SoundEvents.ENTITY_GENERIC_DRINK, 2.25F), "red_meadglass");
        AppetizersInit.register(new AppetizingFoodItem("rewriter", "Chrono Anchor → Dispel", true, 4, 4, SoundEvents.ENTITY_GENERIC_DRINK, 2.25F), "rewriter");
        AppetizersInit.register(new AppetizingFoodItem("rootbeerfloatglass", "", true, 4, 4, SoundEvents.ENTITY_GENERIC_DRINK, 2.25F), "rootbeerfloatglass");
        AppetizersInit.register(new AppetizingFoodItem("rootbeerglass", "", true, 4, 4, SoundEvents.ENTITY_GENERIC_DRINK, 2.25F), "rootbeerglass");
        AppetizersInit.register(new AppetizingFoodItem("royrogers", "", true, 4, 4, SoundEvents.ENTITY_GENERIC_DRINK, 2.25F), "royrogers");
        AppetizersInit.register(new AppetizingFoodItem("rubberneck", "", true, 4, 4, SoundEvents.ENTITY_GENERIC_DRINK, 2.25F), "rubberneck");
        AppetizersInit.register(new AppetizingFoodItem("rumglass", "", true, 4, 4, SoundEvents.ENTITY_GENERIC_DRINK, 2.25F), "rumglass");
        AppetizersInit.register(new AppetizingFoodItem("sakeglass", "", true, 4, 4, SoundEvents.ENTITY_GENERIC_DRINK, 2.25F), "sakeglass");
        AppetizersInit.register(new AppetizingFoodItem("saketokkuri", "", true, 4, 4, SoundEvents.ENTITY_GENERIC_DRINK, 2.25F), "saketokkuri");
        AppetizersInit.register(new AppetizingFoodItem("salvagersdelight", "", true, 4, 4, SoundEvents.ENTITY_GENERIC_DRINK, 2.25F), "salvagersdelight");
        AppetizersInit.register(new AppetizingFoodItem("sapopicante", "", true, 4, 4, SoundEvents.ENTITY_GENERIC_DRINK, 2.25F), "sapopicante");
        AppetizersInit.register(new AppetizingFoodItem("sbitenglass", "", true, 4, 4, SoundEvents.ENTITY_GENERIC_DRINK, 2.25F), "sbitenglass");
        AppetizersInit.register(new AppetizingFoodItem("screwdriverglass", "", true, 4, 4, SoundEvents.ENTITY_GENERIC_DRINK, 2.25F), "screwdriverglass");
        AppetizersInit.register(new AppetizingFoodItem("sdreamglass", "", true, 4, 4, SoundEvents.ENTITY_GENERIC_DRINK, 2.25F), "sdreamglass");
        AppetizersInit.register(new AppetizingFoodItem("shake-blue", "", true, 4, 4, SoundEvents.ENTITY_GENERIC_DRINK, 2.25F), "shake-blue");
        AppetizersInit.register(new AppetizingFoodItem("shake-meat", "", true, 4, 4, SoundEvents.ENTITY_GENERIC_DRINK, 2.25F), "shake-meat");
        AppetizersInit.register(new AppetizingFoodItem("shake-robo", "", true, 4, 4, SoundEvents.ENTITY_GENERIC_DRINK, 2.25F), "shake-robo");
        AppetizersInit.register(new AppetizingFoodItem("shake-white", "", true, 4, 4, SoundEvents.ENTITY_GENERIC_DRINK, 2.25F), "shake-white");
        AppetizersInit.register(new AppetizingFoodItem("shirleytemple", "", true, 4, 4, SoundEvents.ENTITY_GENERIC_DRINK, 2.25F), "shirleytemple");
        AppetizersInit.register(new AppetizingFoodItem("silencerglass", "", true, 4, 4, SoundEvents.ENTITY_GENERIC_DRINK, 2.25F), "silencerglass");
        AppetizersInit.register(new AppetizingFoodItem("silverjack", "", true, 4, 4, SoundEvents.ENTITY_GENERIC_DRINK, 2.25F), "silverjack");
        AppetizersInit.register(new AppetizingFoodItem("singulo", "Don't get sucked in.", true, 4, 4, SoundEvents.ENTITY_GENERIC_DRINK, 2.25F), "singulo");
        AppetizersInit.register(new AppetizingFoodItem("slimeshine", "", true, 4, 4, SoundEvents.ENTITY_GENERIC_DRINK, 2.25F), "slimeshine");
        AppetizersInit.register(new AppetizingFoodItem("snowball", "", true, 4, 4, SoundEvents.ENTITY_GENERIC_DRINK, 2.25F), "snowball");
        AppetizersInit.register(new AppetizingFoodItem("snowwhite", "", true, 4, 4, SoundEvents.ENTITY_GENERIC_DRINK, 2.25F), "snowwhite");
        AppetizersInit.register(new AppetizingFoodItem("sojuglass", "", true, 4, 4, SoundEvents.ENTITY_GENERIC_DRINK, 2.25F), "sojuglass");
        AppetizersInit.register(new AppetizingFoodItem("sol_dry_glass", "", true, 4, 4, SoundEvents.ENTITY_GENERIC_DRINK, 2.25F), "sol_dry_glass");
        AppetizersInit.register(new AppetizingFoodItem("soy_latte", "", true, 4, 4, SoundEvents.ENTITY_GENERIC_DRINK, 2.25F), "soy_latte");
        AppetizersInit.register(new AppetizingFoodItem("space-up_glass", "", true, 4, 4, SoundEvents.ENTITY_GENERIC_DRINK, 2.25F), "space-up_glass");
        AppetizersInit.register(new AppetizingFoodItem("space_mountain_wind_glass", "", true, 4, 4, SoundEvents.ENTITY_GENERIC_DRINK, 2.25F), "space_mountain_wind_glass");
        AppetizersInit.register(new AppetizingFoodItem("specialsundae", "", true, 4, 4, SoundEvents.ENTITY_GENERIC_DRINK, 2.25F), "specialsundae");
        AppetizersInit.register(new AppetizingFoodItem("strayglass", "Meow.", true, 4, 4, SoundEvents.ENTITY_GENERIC_DRINK, 2.25F), "strayglass");
        AppetizersInit.register(new AppetizingFoodItem("sugarglass", "", true, 4, 4, SoundEvents.ENTITY_GENERIC_DRINK, 2.25F, new ApplyEffectsConsumeEffect(new StatusEffectInstance(StatusEffects.SPEED, 600, 3))), "sugarglass");
        AppetizersInit.register(new AppetizingFoodItem("sweetbloodshot", "", true, 4, 4, SoundEvents.ENTITY_GENERIC_DRINK, 2.25F), "sweetbloodshot");
        AppetizersInit.register(new AppetizingFoodItem("syndicatebomb", "Somebody set us up the bomb!", true, 4, 4, SoundEvents.ENTITY_GENERIC_DRINK, 2.25F), "syndicatebomb");
        AppetizersInit.register(new AppetizingFoodItem("syndicatesoverseer", "", true, 4, 4, SoundEvents.ENTITY_GENERIC_DRINK, 2.25F), "syndicatesoverseer");
        AppetizersInit.register(new AppetizingFoodItem("teaglass", "", true, 4, 4, SoundEvents.ENTITY_GENERIC_DRINK, 2.25F), "teaglass");
        AppetizersInit.register(new AppetizingFoodItem("tequillaglass", "", true, 4, 4, SoundEvents.ENTITY_GENERIC_DRINK, 2.25F), "tequillaglass");
        AppetizersInit.register(new AppetizingFoodItem("tequillasunriseglass", "", true, 4, 4, SoundEvents.ENTITY_GENERIC_DRINK, 2.25F), "tequillasunriseglass");
        AppetizersInit.register(new AppetizingFoodItem("the_martinez", "You didn't take me to the moon, but you were there with me.", true, 4, 4, SoundEvents.ENTITY_GENERIC_DRINK, 2.25F), "the_martinez");
        AppetizersInit.register(new AppetizingFoodItem("thesunalsorises", "", true, 4, 4, SoundEvents.ENTITY_GENERIC_DRINK, 2.25F), "thesunalsorises");
        AppetizersInit.register(new AppetizingFoodItem("thewaterslide", "", true, 4, 4, SoundEvents.ENTITY_GENERIC_DRINK, 2.25F), "thewaterslide");
        AppetizersInit.register(new AppetizingFoodItem("threemileislandglass", "", true, 4, 4, SoundEvents.ENTITY_GENERIC_DRINK, 2.25F), "threemileislandglass");
        AppetizersInit.register(new AppetizingFoodItem("tonicglass", "", true, 4, 4, SoundEvents.ENTITY_GENERIC_DRINK, 2.25F), "tonicglass");
        AppetizersInit.register(new AppetizingFoodItem("torpedojuice", "", true, 4, 4, SoundEvents.ENTITY_GENERIC_DRINK, 2.25F), "torpedojuice");
        AppetizersInit.register(new AppetizingFoodItem("tortuga", "", true, 4, 4, SoundEvents.ENTITY_GENERIC_DRINK, 2.25F), "tortuga");
        AppetizersInit.register(new AppetizingFoodItem("toxinsspecialglass", "I wouldn't drink this if I were you.", true, 4, 4, SoundEvents.ENTITY_GENERIC_DRINK, 2.25F, new ApplyEffectsConsumeEffect(toxins)), "toxinsspecialglass");
        AppetizersInit.register(new AppetizingFoodItem("triplecitrus", "", true, 4, 4, SoundEvents.ENTITY_GENERIC_DRINK, 2.25F), "triplecitrus");
        AppetizersInit.register(new AppetizingFoodItem("vampiro", "", true, 4, 4, SoundEvents.ENTITY_GENERIC_DRINK, 2.25F, new ApplyEffectsConsumeEffect(new StatusEffectInstance(StatusEffects.REGENERATION, 600, 3))), "vampiro");
        AppetizersInit.register(new AppetizingFoodItem("vermouthglass", "", true, 4, 4, SoundEvents.ENTITY_GENERIC_DRINK, 2.25F), "vermouthglass");
        AppetizersInit.register(new AppetizingFoodItem("vodkatonicglass", "", true, 4, 4, SoundEvents.ENTITY_GENERIC_DRINK, 2.25F), "vodkatonicglass");
        AppetizersInit.register(new AppetizingFoodItem("voltage", "Short Circuit Crash!! not included.", true, 4, 4, SoundEvents.ENTITY_GENERIC_DRINK, 2.25F), "voltage");
        AppetizersInit.register(new AppetizingFoodItem("wakeupjuice", "", true, 4, 4, SoundEvents.ENTITY_GENERIC_DRINK, 2.25F), "wakeupjuice");
        AppetizersInit.register(new AppetizingFoodItem("wassail", "", true, 4, 4, SoundEvents.ENTITY_GENERIC_DRINK, 2.25F), "wassail");
        AppetizersInit.register(new AppetizingFoodItem("watermelonjuice", "", true, 4, 4, SoundEvents.ENTITY_GENERIC_DRINK, 2.25F), "watermelonjuice");
        AppetizersInit.register(new AppetizingFoodItem("watermelonglass", "", true, 4, 4, SoundEvents.ENTITY_GENERIC_DRINK, 2.25F), "watermelonglass");
        AppetizersInit.register(new AppetizingFoodItem("whiskeycolaglass", "", true, 4, 4, SoundEvents.ENTITY_GENERIC_DRINK, 2.25F), "whiskeycolaglass");
        AppetizersInit.register(new AppetizingFoodItem("whiskeyglass", "", true, 4, 4, SoundEvents.ENTITY_GENERIC_DRINK, 2.25F), "whiskeyglass");
        AppetizersInit.register(new AppetizingFoodItem("whiskeysodaglass", "", true, 4, 4, SoundEvents.ENTITY_GENERIC_DRINK, 2.25F), "whiskeysodaglass");
        AppetizersInit.register(new AppetizingFoodItem("whiskeysodaglass2", "", true, 4, 4, SoundEvents.ENTITY_GENERIC_DRINK, 2.25F), "whiskeysodaglass2");
        AppetizersInit.register(new AppetizingFoodItem("whiskeysour", "", true, 4, 4, SoundEvents.ENTITY_GENERIC_DRINK, 2.25F), "whiskeysour");
        AppetizersInit.register(new AppetizingFoodItem("whiterussianglass", "", true, 4, 4, SoundEvents.ENTITY_GENERIC_DRINK, 2.25F), "whiterussianglass");
        AppetizersInit.register(new AppetizingFoodItem("wineglass", "", true, 4, 4, SoundEvents.ENTITY_GENERIC_DRINK, 2.25F), "wineglass");
        AppetizersInit.register(new AppetizingFoodItem("xenobasher", "", true, 4, 4, SoundEvents.ENTITY_GENERIC_DRINK, 2.25F), "xenobasher");
        AppetizersInit.register(new AppetizingFoodItem("zombiecocktail", "", true, 4, 4, SoundEvents.ENTITY_GENERIC_DRINK, 2.25F), "zombiecocktail");
    }

    static {
        atpunch.add(new StatusEffectInstance(StatusEffects.SPEED, 600, 1));
        atpunch.add(new StatusEffectInstance(StatusEffects.RESISTANCE, 600, 1));
        atpunch.add(new StatusEffectInstance(StatusEffects.REGENERATION, 600, 1));

        ddelight.add(new StatusEffectInstance(StatusEffects.REGENERATION, 600, 3));
        ddelight.add(new StatusEffectInstance(StatusEffects.ABSORPTION, 600, 3));
        ddelight.add(new StatusEffectInstance(StatusEffects.INSTANT_HEALTH, 1, 1));
        ddelight.add(new StatusEffectInstance(StatusEffects.RESISTANCE, 600, 1));

        drblood.add(new StatusEffectInstance(StatusEffects.FIRE_RESISTANCE, 3000));
        drblood.add(new StatusEffectInstance(StatusEffects.REGENERATION, 600, 3));
        drblood.add(new StatusEffectInstance(StatusEffects.RESISTANCE, 600, 3));

        drbreath.add(new StatusEffectInstance(StatusEffects.FIRE_RESISTANCE, 6000));
        drbreath.add(new StatusEffectInstance(StatusEffects.RESISTANCE, 600, 1));
        drbreath.add(new StatusEffectInstance(StatusEffects.REGENERATION, 600, 1));

        floko.add(new StatusEffectInstance(StatusEffects.SPEED, 600, 4));
        floko.add(new StatusEffectInstance(StatusEffects.HASTE, 600, 4));
        floko.add(new StatusEffectInstance(StatusEffects.POISON, 600, 9));
        floko.add(new StatusEffectInstance(StatusEffects.WITHER, 600, 9));

        toxins.add(new StatusEffectInstance(StatusEffects.POISON, 600, 4));
        toxins.add(new StatusEffectInstance(StatusEffects.WITHER, 600, 4));
        toxins.add(new StatusEffectInstance(StatusEffects.BLINDNESS, 600));
        toxins.add(new StatusEffectInstance(StatusEffects.NAUSEA, 600));
        toxins.add(new StatusEffectInstance(StatusEffects.SLOWNESS, 600, 4));
        toxins.add(new StatusEffectInstance(StatusEffects.HUNGER, 600, 4));
        toxins.add(new StatusEffectInstance(StatusEffects.UNLUCK, 600, 4));
        toxins.add(new StatusEffectInstance(StatusEffects.MINING_FATIGUE, 600, 4));
        toxins.add(new StatusEffectInstance(StatusEffects.WEAKNESS, 600, 4));
    }
}
